### ISSUE TITLE
Running a command gets stuck in Rails 4.2.5

### ISSUE THREAD

**Issue by bobf** [thegarage/thor-rails#5]
Hi, not sure what's causing this but I am doing the following:

``` bash
$ rails new test_thor_rails
$ cd test_thor_rails
# Add `thor-rails` to Gemfile
$ bundle install
# Create `lib/tasks/test.thor` from example given here: https://github.com/thegarage/thor-rails#usage
$ thor my_command:do_something
```

And then the ruby process consumes 100% of my CPU until I interrupt it, at which point I get a stack trace along the lines of:

```
/Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/basic_specification.rb:62:in `block (2 levels) in contains_requirable_file?': Interrupt
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/basic_specification.rb:62:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/basic_specification.rb:62:in `any?'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/basic_specification.rb:62:in `block in contains_requirable_file?'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/basic_specification.rb:60:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/basic_specification.rb:60:in `any?'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/basic_specification.rb:60:in `contains_requirable_file?'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:951:in `block (2 levels) in find_in_unresolved_tree'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2397:in `[]'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2397:in `block (2 levels) in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `block in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2398:in `block (2 levels) in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `block in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2398:in `block (2 levels) in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `block in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2398:in `block (2 levels) in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `block in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2398:in `block (2 levels) in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2396:in `block in traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:2395:in `traverse'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:949:in `block in find_in_unresolved_tree'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:947:in `reverse_each'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/specification.rb:947:in `find_in_unresolved_tree'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:93:in `require'
	from /Users/bobfarrell/dev/test_thor_rails/config/boot.rb:3:in `<top (required)>'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/bobfarrell/dev/test_thor_rails/config/application.rb:1:in `<top (required)>'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/bobfarrell/dev/test_thor_rails/config/environment.rb:2:in `<top (required)>'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/thor-rails-0.0.1/lib/thor/rails.rb:23:in `load_environment'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/thor-rails-0.0.1/lib/thor/rails.rb:15:in `start'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/runner.rb:36:in `method_missing'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/thor-0.19.1/bin/thor:6:in `<top (required)>'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/bin/thor:23:in `load'
	from /Users/bobfarrell/.rbenv/versions/2.1.6/bin/thor:23:in `<main>'
```

Some kind of circular dependency issue ?

Let me know if you need more info.

**Comment by bobf** [comment]
My `Gemfile.lock` in case that's also useful:

``` Gemfile
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.5)
      actionview (= 4.2.5)
      activesupport (= 4.2.5)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.5)
      activesupport (= 4.2.5)
      globalid (>= 0.3.0)
    activemodel (4.2.5)
      activesupport (= 4.2.5)
      builder (~> 3.1)
    activerecord (4.2.5)
      activemodel (= 4.2.5)
      activesupport (= 4.2.5)
      arel (~> 6.0)
    activesupport (4.2.5)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    byebug (8.2.1)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    concurrent-ruby (1.0.0)
    debug_inspector (0.0.2)
    erubis (2.7.0)
    execjs (2.6.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    i18n (0.7.0)
    jbuilder (2.4.0)
      activesupport (>= 3.0.0, < 5.1)
      multi_json (~> 1.2)
    jquery-rails (4.1.0)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.99)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    multi_json (1.11.2)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.5)
      actionmailer (= 4.2.5)
      actionpack (= 4.2.5)
      actionview (= 4.2.5)
      activejob (= 4.2.5)
      activemodel (= 4.2.5)
      activerecord (= 4.2.5)
      activesupport (= 4.2.5)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.5)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (4.2.5)
      actionpack (= 4.2.5)
      activesupport (= 4.2.5)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.5.0)
    rdoc (4.2.1)
      json (~> 1.4)
    sass (3.4.21)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    spring (1.6.2)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.0.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.11)
    thor (0.19.1)
    thor-rails (0.0.1)
      rails
      thor
    thread_safe (0.3.5)
    tilt (2.0.2)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)

PLATFORMS
  ruby

DEPENDENCIES
  byebug
  coffee-rails (~> 4.1.0)
  jbuilder (~> 2.0)
  jquery-rails
  rails (= 4.2.5)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  spring
  sqlite3
  thor-rails
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.10.0.rc
```

**Comment by chris-nelson-mn** [comment]
Hi Bob,

So I used your example to try and reproduce. After running `my_command:do_something` my machine churns along with one CPU core pegged at 100% for about 30 seconds, then I get the following:

```
chrisnelson@ChrisNelsonsMBP test_thor_rails$ thor my_command:do_something
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7)
      thread_safe (>= 0.3.4, ~> 0.1, ~> 0.3)
      minitest (~> 5.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-html-sanitizer (>= 1.0.2, ~> 1.0)
      rails-dom-testing (>= 1.0.5, ~> 1.0)
      arel (~> 6.0)
      globalid (>= 0.3.0)
      mail (>= 2.5.4, ~> 2.5)
      rake (>= 0.8.7)
      sprockets-rails (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
development
```

However, if I use `bundle exec thor my_command:do_something` it very quickly returns with `development`. So for now simply running with `bundle exec` is my recommended workaround, and I will update the README to that effect. To be honest I don't have the bandwidth to give this gem a lot of support. If you have time to keep trying to run down the issue and want to submit a PR, I'd be happy to review it and pull it in if it fixes the problem.

**Comment by bobf** [comment]
Thanks for taking the time to look, Chris, I know how hard it can be to find any time at all for open source stuff. :)

My current workaround is to just `require './config/environment'` which removes the need for the gem. But it'd be nice to use the gem as I'm sure my workaround won't cover all bases so would be good to have a common place to put any extras.

So if I find that the above doesn't work out well for me in the long term then I'll take another look at the gem.

All the best,
